# Generated by Django 5.0.3 on 2024-03-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funcionarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionarios",
            name="edv",
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name="funcionarios",
            name="endereco",
            field=models.TextField(unique=True),
        ),
    ]
