# Generated by Django 5.0.3 on 2024-03-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produtos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=200)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tensao",
                    models.CharField(
                        choices=[("110V", "110 Volts"), ("220V", "220 Volts")],
                        max_length=4,
                    ),
                ),
                ("marca", models.CharField(max_length=50)),
            ],
        ),
    ]
