# Generated by Django 5.0.3 on 2024-03-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtos",
            name="peso",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="produtos",
            name="tipo",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="produtos",
            name="tensao",
            field=models.CharField(
                choices=[("110V", "110 Volts"), ("220V", "220 Volts")],
                default="Escolha uma opção",
                max_length=4,
            ),
        ),
    ]
