# Generated by Django 5.0.3 on 2024-03-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0003_alter_produtos_peso"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtos",
            name="quantidade",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
